# Name your project! Project names should contain only lowercase characters
# and underscores.
name: 'agro_credit_transform'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
# Deve ser igual ao nome que está no topo do seu ~/.dbt/profiles.yml
profile: 'agro_credit_transform'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  agro_credit_transform:
    +materialized: view
    
    # Pasta staging -> Grava no dataset 'agro_esg_staging'
    staging:
      +schema: agro_esg_staging
      +materialized: view

    # Pasta intermediate -> (Você não listou esse dataset, sugiro criar 'agro_esg_intermediate')
    # Se não quiser criar agora, pode jogar na staging também, mas o ideal é separar.
    intermediate:
      +schema: agro_esg_intermediate  # Temporário, ou crie o dataset 'agro_esg_intermediate'
      +materialized: table

    # Pasta marts -> Grava no dataset 'agro_esg_marts'
    marts:
      +schema: agro_esg_marts
      +materialized: table