name: 'agro_credit_transform'
version: '1.0.0'
config-version: 2

profile: 'agro_credit_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# ---------------------------------------------------------------
# 1. VARIÁVEIS GLOBAIS (Onde a mágica acontece)
# ---------------------------------------------------------------
vars:
  # Data do Marco Temporal (Código Florestal)
  forest_code_threshold_date: '2008-07-22'
  
  # Limite de tolerância para ruído de GPS/GIS (em hectares)
  gis_noise_ha_threshold: 0.1
  
  # Limite de tolerância percentual (0.005 = 0.5% da área da propriedade)
  gis_noise_pct_threshold: 0.005

# ---------------------------------------------------------------
# 2. CONFIGURAÇÃO DOS MODELOS
# ---------------------------------------------------------------
models:
  agro_credit_transform:
    +materialized: view
    
    # Camada de Limpeza e Padronização
    staging:
      +schema: agro_esg_staging
      +materialized: view

    # Camada de Transformação e Joins Complexos
    intermediate:
      +schema: agro_esg_intermediate
      +materialized: table # Recomendado table para performance em joins espaciais

    # Camada de Negócio e Consumo (Dashboards/API)
    marts:
      +schema: agro_esg_marts
      +materialized: table