version: 2

sources:
  - name: raw_data  # Nome interno que usaremos no dbt: {{ source('raw_data', 'tabela') }}
    project: "{{ env_var('GCP_PROJECT_ID') }}" # Pega do .env
    dataset: agro_esg_raw # O dataset que as DAGs e Scripts populam
    
    tables:
      - name: sigef_history
        description: "Dados brutos das propriedades rurais vindos do SIGEF."
        columns:
          - name: file_hash
            description: "Hash MD5 do arquivo original para controle de idempotência."

      - name: ibama_history
        description: "Lista bruta de áreas embargadas pelo IBAMA."
        columns:
          - name: file_hash
            description: "Hash MD5 do arquivo original para controle de idempotência."

      - name: ibge_biomes  # <--- NOVA TABELA ADICIONADA AQUI
        description: "Dados espaciais dos Biomas Brasileiros (IBGE - Escala 1:250.000)."
        columns:
          - name: file_hash
            description: "Hash MD5 do arquivo original (Shapefile/Zip)."
          - name: wkt_geometry
            description: "Geometria do bioma em formato WKT (Texto), convertida para EPSG:4326."