version: 2

sources:
  - name: raw_data
    description: "Landing Zone: Dados brutos de fontes externas (SIGEF, IBAMA, CAR, MTE, GEE) populados via Airflow/DuckDB."
    project: "{{ env_var('GCP_PROJECT_ID') }}"
    dataset: agro_esg_raw

    tables:
      # --- INFRAESTRUTURA E TOPOGRAFIA (GEE) ---
      - name: raw_ee_topography
        description: "Dados brutos de elevação e declividade extraídos do Google Earth Engine."
        columns:
          - name: property_id
            description: "ID único da propriedade (vinculado ao CAR/SIGEF)."
          - name: max_slope
            description: "Declividade máxima encontrada no polígono."

      # --- REGULARIDADE FUNDIÁRIA E AMBIENTAL ---
      - name: sigef_history
        description: "Histórico de certificações de imóveis rurais no SIGEF."
        columns: &hash_control
          - name: file_hash
            description: "Hash MD5 do arquivo original para controle de idempotência."

      - name: car_area_imovel_geometria
        description: "Geometria espacial (WKT) das propriedades rurais do CAR."
        columns:
          - <<: *hash_control
          - name: wkt_geom
            description: "Geometria em formato WKT (EPSG:4326)."

      - name: car_metadados_proprietarios
        description: "Metadados de detentores e datas de registro do CAR."

      - name: car_temas_ambientais
        description: "Vetores de APP, Reserva Legal e Uso Consolidado (CSV/Parquet)."

      - name: car_sobreposicao
        description: "Cálculos de sobreposição nativos do SICAR com TIs e UCs."

      # --- RESTRITIVOS SOCIOAMBIENTAIS E BIOMAS ---
      - name: ibama_history
        description: "Histórico de áreas embargadas pelo IBAMA."
        columns: *hash_control

      - name: mte_slave_labor_history
        description: "Lista Suja do MTE - Trabalho análogo à escravidão."
        columns:
          - <<: *hash_control
          - name: cnpjcpf
            description: "CPF/CNPJ do infrator para cruzamento de malha."

      - name: ibge_biomes
        description: "Malha digital de biomas brasileiros (Escala 1:250.000)."
        columns:
          - <<: *hash_control
          - name: wkt_geometry
            description: "Geometria convertida para EPSG:4326."

      # --- TERRITÓRIOS PROTEGIDOS E HIDROGRAFIA ---
      - name: funai_terras_indigenas  
        description: "Polígonos de Terras Indígenas (FUNAI) em todas as fases."
        columns: *hash_control

      - name: incra_quilombolas
        description: "Territórios Quilombolas delimitados pelo INCRA."
        columns: *hash_control

      - name: ana_app_zones
        description: "Zonas de APP geradas via DuckDB (BHO Nível 07 - Strahler)."
        columns:
          - name: wkt_geom_app
            description: "Polígono da APP (EPSG:4326)."

      - name: ibge_bc250_app_zones
        description: "Zonas de APP de massas d'água (lagos/represas) da BC250."
